function M_mtrx = M_mtrx(in1)
%M_MTRX
%    M_MTRX = M_MTRX(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    04-Dec-2019 21:10:45

q2 = in1(2,:);
t2 = cos(q2);
t3 = t2.*(4.9e1./2.0e1);
t4 = t3+3.43e2./4.0e2;
M_mtrx = reshape([t2.*(4.9e1./1.0e1)+1.03575e1,t4,t4,3.43e2./4.0e2],[2,2]);
