function n_vctr = n_vctr(in1,in2)
%N_VCTR
%    N_VCTR = N_VCTR(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    04-Dec-2019 21:10:46

q2 = in1(2,:);
q1d = in2(1,:);
q2d = in2(2,:);
t2 = sin(q2);
n_vctr = [q2d.*t2.*(q1d.*2.0+q2d).*(-4.9e1./2.0e1);q1d.^2.*t2.*(4.9e1./2.0e1)];
