function alfa_num = alfa_fcn(s)
%ALFA_FCN
%    ALFA_NUM = ALFA_FCN(S)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    16-Apr-2019 12:28:51

alfa_num = cos(s-sin(s).*(8.0./5.0))-cos(s).*(8.0./5.0)+1.0;
