function bta_num = beta_fcn(s)
%BETA_FCN
%    BTA_NUM = BETA_FCN(S)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    16-Apr-2019 12:28:51

bta_num = sin(s).*(8.0./5.0);
