function gma_num = gamma_fcn(s)
%GAMMA_FCN
%    GMA_NUM = GAMMA_FCN(S)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    16-Apr-2019 12:28:51

gma_num = sin(s-sin(s).*(8.0./5.0)).*(-9.81e2./1.0e2);
