function M_mtrx = M_mtrx(in1)
%M_MTRX
%    M_MTRX = M_MTRX(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    28-Nov-2019 15:41:32

thta = in1(2,:);
t2 = cos(thta);
t3 = t2.*(3.0./2.0e1);
M_mtrx = reshape([1.3e1./1.0e1,t3,t3,3.0./4.0e1],[2,2]);
